/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_hodlwallet_core_BRCorePaymentProtocolACK */

#ifndef _Included_co_hodlwallet_core_BRCorePaymentProtocolACK
#define _Included_co_hodlwallet_core_BRCorePaymentProtocolACK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    getCustomerMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_getCustomerMemo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    getMerchantData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_getMerchantData
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    getTransactions
 * Signature: ()[Lco/_hodlwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_getTransactions
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    getRefundTo
 * Signature: ()[Lco/_hodlwallet/core/BRCoreTransactionOutput;
 */
JNIEXPORT jobjectArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_getRefundTo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    getMerchantMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_getMerchantMemo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    createPaymentProtocolACK
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_createPaymentProtocolACK
(JNIEnv *, jclass, jbyteArray);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_serialize
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_disposeNative
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolACK
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolACK_initializeNative
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
