/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_hodlwallet_core_BRCorePaymentProtocolPaymentACK */

#ifndef _Included_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
#define _Included_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    getCustomerMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_getCustomerMemo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    getMerchantData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_getMerchantData
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    getTransactions
 * Signature: ()[Lco/_hodlwallet/core/BRCoreTransaction;
 */
JNIEXPORT jobjectArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_getTransactions
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    getRefundTo
 * Signature: ()[Lco/_hodlwallet/core/BRCoreTransactionOutput;
 */
JNIEXPORT jobjectArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_getRefundTo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    getMerchantMemo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_getMerchantMemo
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    createPaymentProtocolPaymentACK
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_createPaymentProtocolPaymentACK
(JNIEnv *, jclass, jbyteArray);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    serialize
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_serialize
(JNIEnv *, jobject);

/*
 * Class:     co_hodlwallet_core_BRCorePaymentProtocolPaymentACK
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_co_hodlwallet_core_BRCorePaymentProtocolPaymentACK_disposeNative
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
